  name: pusher_client_ego
  description: " A lightweight Flutter client for Pusher Channels, supporting public, private, and presence channels with real-time event binding and client event triggering — inspired by the official pusher-js library."
  repository: https://github.com/OmarAly92/pusher_client_EGO

  version: 1.0.0+2

  environment:
    sdk: ^3.8.1

  dependencies:
    flutter:
      sdk: flutter
    dio: ^5.8.0+1

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^6.0.0

  flutter:
    uses-material-design: true